version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: ${APP_NAME}:development
    container_name: ${APP_NAME}-dev
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    command:
      - "yarn"
      - "dev"

  adminer:
    image: adminer:latest
    container_name: ${APP_NAME}-adminer
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: ${APP_NAME}-db
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
